on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  list-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: '3.10' # Set the Python version to use.
      - name: List configs
        id: ls
        run: |
          configs=$(python -c "import glob, json; print(json.dumps(sorted(glob.glob('configs/*.pkg'))))")
          names=$(python -c "import os, glob, json; print(json.dumps(sorted([os.path.basename(it).split('.')[0] for it in glob.glob('configs/*.pkg')])))")
          echo "names=$names" >> $GITHUB_OUTPUT
          echo "configs=$configs" >> $GITHUB_OUTPUT
    outputs:
      configs: ${{ steps.ls.outputs.configs }}
      names: ${{ steps.ls.outputs.names }}
  build-data:
    runs-on: ubuntu-latest
    needs: list-configs
    strategy:
      matrix:
        config: ${{ fromJson(needs.list-configs.outputs.configs) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Set the Python version to use.
      - name: Install eagerbib
        run: pip install git+https://github.com/zimmerrol/eagerbib.git
      - name: Build data
        id: eagerbib-crawler
        run: |
          configbn=$(basename -- "${{ matrix.config }}")
          configbn="${configbn%.*}"
          echo "configbn=$configbn" >> $GITHUB_OUTPUT
          eagerbib-crawler --config ${{ matrix.config }} -o data/$configbn
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.eagerbib-crawler.outputs.configbn }}
          path: data/${{ steps.eagerbib-crawler.outputs.configbn }}.tar.gz
  upload-data:
    runs-on: ubuntu-latest
    needs: build-data
    steps:
      - uses: actions/checkout@v3
        with:
          ref: data
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Set the Python version to use.
      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          path: data
      - name: Aggregate data
        run: |
          cd data
          ls .
          find . -name '*.tar.gz' -type f -print -exec mv {} . \;
          find . -type d -empty -delete
          ls .
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.tar.gz
          git commit -a -m "Update dblp bibliography packages"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: data
